### PR TITLE
do not report failures in skipped tests

### LINKED ISSUE #6: Do not report `@pytest.mark.skipIf` exceptions
We frequently use `@pytest.mark.skipIf` in our test-suite to skip tests that are not runnable in the current environment.

Sadly `pytest-sentry` does not support `@pytest.mark.skipIf`, since it uses exceptions internally to signal whether a test was skipped or not, we get loads of exceptions reported to sentry that are little more than the skipped tests. So much so that ~90% of our sentry quota would be used by skipped tests, and exhausting the quota before we get really helpful exceptions flagged.

It'd be nice to have a way to opt out of reporting these to sentry at all. I know there's server-side filtering, but that's a premium feature that's not well-suited to an open-source project.

### PR DESCRIPTION
**Pull request by asottile-sentry**
resolves #6

### CODE REVIEW

**Comment by untitaker** [comment]
looks fine, can you add a test though? I think the testsuite is pretty much the only thing we have to know whether pytest upgrade would break things

**Comment by asottile-sentry** [comment]
> looks fine, can you add a test though? I think the testsuite is pretty much the only thing we have to know whether pytest upgrade would break things

I couldn't get the existing testsuite running locally -- it seems to always fail?

**Comment by untitaker** [comment]
I see you're with pytest 7, it's possible that we pytest-sentry is broken for newer pytest already

**Comment by asottile-sentry** [comment]
oh I was missing the rerunning thing :thinking:  seems to pass now

**Comment by untitaker** [comment]
"somebody" (me prob) should set up CI for this. last CI here was travis at best

**Comment by asottile-sentry** [comment]
actually the current `tests/test_skip.py` are broken and this patch fixes them:

```console
$ PYTEST_SENTRY_ALWAYS_REPORT=1 pytest tests/test_skip.py 
you forgot to activate ./venv -- I gotchu
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/asottile/workspace/pytest-sentry
plugins: rerunfailures-10.2, sentry-0.1.9
collected 4 items                                                              

tests/test_skip.py ssXxR                                                 [100%]xR [100%]xE [100%]

==================================== ERRORS ====================================
_______________________ ERROR at teardown of test_xfail ________________________

    @pytest.fixture(scope="session", autouse=True)
    def assert_report():
        yield
>       assert not events
E       AssertionError: assert not [{'_meta': {'exception': {'values': {'0': {'stacktrace': {...}}}}}, 'breadcrumbs': {'values': []}, 'contexts': {'runti...: 'pytest.runtest.protocol', 'parent_span_id': None, 'span_id': 'af79841e33695276', ...}}, 'environment': 'test', ...}]

tests/test_skip.py:39: AssertionError
=========================== short test summary info ============================
ERROR tests/test_skip.py::test_xfail - AssertionError: assert not [{'_meta': {'exception': {'values': {'0': {'stac...
========== 2 skipped, 3 xfailed, 1 xpassed, 1 error, 2 rerun in 0.14s ==========
$ git checkout -- .
$ PYTEST_SENTRY_ALWAYS_REPORT=1 pytest tests/test_skip.py 
you forgot to activate ./venv -- I gotchu
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/asottile/workspace/pytest-sentry
plugins: rerunfailures-10.2, sentry-0.1.9
collected 4 items                                                              

tests/test_skip.py ssXx                                                  [100%]

=================== 2 skipped, 1 xfailed, 1 xpassed in 0.08s ===================
```

**Review by untitaker — APPROVED** [review]
cool, i guess we just need a proper pytest version matrix in CI or tox.ini eventually

**Comment by asottile-sentry** [comment]
I'll try and set something up :+1:

**Pull request merged**
